import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {loadExtensionClass} from './helpers/bw-extensions.mjs';
import {runPxtArcade} from './helpers/pxt-arcade-runtime.mjs';
const Arcade=loadExtensionClass('arcade');
const prop=(a,id,p)=>a.spriteProperty({ID:id,PROPERTY:p});
const cases=[[2,0],[.5,3],[1.333,12],[0,2],[-3,1],[1.007,5]];
function setup(){const a=new Arcade(new EventEmitter()),image=a.createImage({WIDTH:4,HEIGHT:4});a.mutateImage({IMAGE:image,OP:'fill',COLOR:2});const id=a.createImageSprite({IMAGE:image,KIND:'Player'});a.setSpritePosition({ID:id,X:40.25,Y:50.75});return {a,id,image};}
test('scale metadata exposes actual axis properties and scale operations',()=>{const a=new Arcade(new EventEmitter());for(const op of ['setSpriteScale','changeSpriteScale','setSpriteScaleCore'])assert.ok(a.getInfo().blocks.some(b=>b.opcode===op));for(const p of ['sx','sy','scale'])assert.ok(a.getInfo().menus.spriteProperties.items.includes(p));});
test('scale dimensions, anchors and source-image pixels stay separate',()=>{const {a,id}=setup();a.setSpriteScale({ID:id,VALUE:2,ANCHOR:3});assert.equal(prop(a,id,'width'),8);assert.equal(prop(a,id,'left'),38.25);assert.equal(prop(a,id,'top'),48.75);assert.equal(a._scaledSpriteImage(a._sprite(id)).pixels.length,64);assert.deepEqual(a._wallHitbox(a._sprite(id)),{left:0,top:0,width:8,height:8});a.setSpriteProperty({ID:id,PROPERTY:'sy',VALUE:0});assert.equal(prop(a,id,'height'),0);assert.equal(a._scaledSpriteImage(a._sprite(id)).pixels.length,0);a.changeSpriteScale({ID:id,VALUE:.5,ANCHOR:0});assert.equal(prop(a,id,'sx'),2.5);assert.equal(prop(a,id,'sy'),.5);});
test('pinned original verifies fixed point scale properties, optional proportional axes, anchors, image replacement, overlap and hitbox reset',async()=>{
const source=`let actor=sprites.create(img\`2222\n2222\n2222\n2222\`,SpriteKind.Player);actor.setPosition(40.25,50.75);`+cases.map(([scale,anchor],i)=>`actor.setScale(${scale},${anchor});let sx${i}=actor.sx;let sy${i}=actor.sy;let width${i}=actor.width;let height${i}=actor.height;let x${i}=actor.x;let y${i}=actor.y;let left${i}=actor.left;let top${i}=actor.top;`).join('')+`actor.setScaleCore(2,undefined,ScaleAnchor.Middle,true);let proportionalY=actor.sy;actor.changeScale(.5,ScaleAnchor.BottomRight);let changedX=actor.x;let changedY=actor.y;let changedSx=actor.sx;let changedSy=actor.sy;actor.setImage(img\`22\n22\`);let imageWidth=actor.width;let imageHeight=actor.height;let imageX=actor.x;let imageY=actor.y;
let a=sprites.create(img\`2.2\n.2.\n2.2\`,SpriteKind.Player);let b=sprites.create(img\`..2\n2..\n..2\`,SpriteKind.Food);a.setPosition(70,60);b.setPosition(70,60);`+[.25,.5,1,1.5,2,2.75,0].map((s,i)=>`a.sx=${s};a.sy=${s*1.5};b.sx=${s+1};b.sy=.75;let overlap${i}=a.overlapsWith(b);let overlapReverse${i}=b.overlapsWith(a);`).join('');
const p=await runPxtArcade(source);const {a,id}=setup();for(const [i,[value,anchor]] of cases.entries()){a.setSpriteScale({ID:id,VALUE:value,ANCHOR:anchor});for(const key of ['sx','sy','width','height','x','y','left','top'])assert.equal(prop(a,id,key),p[key+i],key+' case '+i);}
a.setSpriteScaleCore({ID:id,SX:2,SY:undefined,ANCHOR:0,PROPORTIONAL:true});assert.equal(prop(a,id,'sy'),p.proportionalY);a.changeSpriteScale({ID:id,VALUE:.5,ANCHOR:12});for(const [key,name] of [['x','changedX'],['y','changedY'],['sx','changedSx'],['sy','changedSy']])assert.equal(prop(a,id,key),p[name]);const image=a.createImage({WIDTH:2,HEIGHT:2});a.setSpriteImage({ID:id,IMAGE:image});for(const [key,name] of [['width','imageWidth'],['height','imageHeight'],['x','imageX'],['y','imageY']])assert.equal(prop(a,id,key),p[name]);
function masked(pixels){const image=a.createImage({WIDTH:3,HEIGHT:3});for(const [i,color]of pixels.entries())a.setImagePixel({IMAGE:image,X:i%3,Y:(i/3)|0,COLOR:color});const h=a.createImageSprite({IMAGE:image,KIND:'Player'});a.setSpritePosition({ID:h,X:70,Y:60});return h;}
const first=masked([2,0,2,0,2,0,2,0,2]),second=masked([0,0,2,2,0,0,0,0,2]);for(const[i,s]of [.25,.5,1,1.5,2,2.75,0].entries()){for(const[h,key,value]of [[first,'sx',s],[first,'sy',s*1.5],[second,'sx',s+1],[second,'sy',.75]])a.setSpriteProperty({ID:h,PROPERTY:key,VALUE:value});assert.equal(a.spriteOverlaps({A:first,B:second}),p['overlap'+i],'overlap '+i);assert.equal(a.spriteOverlaps({A:second,B:first}),p['overlapReverse'+i],'reverse overlap '+i);}
});
test('canonical imported costume scales through a real raster skin and preserves scale on costume replacement',()=>{
 const svg='<svg width="16" height="16" shape-rendering="crispEdges"><rect x="0" y="0" width="16" height="16" fill="#ff2121"/></svg>',costume={dataFormat:'svg',rotationCenterX:8,rotationCenterY:8,asset:{data:svg}};
 const r=new EventEmitter(),skins=[],clone={drawableID:1,currentCostume:0,size:100,setSize(n){this.size=n;},setVisible(){},setXY(){},setCostume(){},getCostumes(){return[costume];}};
 r.getSpriteTargetByName=()=>({makeClone:()=>clone});r.addTarget=()=>{};r.renderer={createSVGSkin(svg,center){skins.push({svg,center});return skins.length;},updateSVGSkin(id,svg,center){skins.push({svg,center});},updateDrawableSkinId(){},updateDrawableProperties(){},destroySkin(){}};
 const a=new Arcade(r),id=a.createSprite({TEMPLATE:'Art',KIND:'Player',WIDTH:4,HEIGHT:4});a.setSpriteScale({ID:id,VALUE:2,ANCHOR:0});assert.equal(prop(a,id,'width'),8);assert.match(skins.at(-1).svg,/width="32"/);assert.deepEqual(skins.at(-1).center,[16,16]);a.setSpriteCostume({ID:id,COSTUME:0});assert.equal(prop(a,id,'width'),8);assert.match(skins.at(-1).svg,/width="32"/);
});
test('original scaled transparent hitbox expands wall geometry and scale setters resolve real contacts',async()=>{
 const source=`tiles.setTilemap(tiles.createTilemap(hex\`0400040000000000000000000000000000000000\`,img\`0 0 2 0\n0 0 2 0\n0 0 2 0\n0 0 2 0\`,[img\`0\`],TileScale.Eight));let actor=sprites.create(img\`020\n222\n020\`,SpriteKind.Player);actor.setPosition(12,12);actor.setScale(2);let scaleX=actor.x;let scaleY=actor.y;actor.vx=100;game.currentScene().physicsEngine.move(.1);let contactX=actor.x;let contactVx=actor.vx;let contactRight=actor.isHittingTile(CollisionDirection.Right);actor.sx=.5;let resizedX=actor.x;let resizedWidth=actor.width;`;
 const p=await runPxtArcade(source),a=new Arcade(new EventEmitter());a.setTilemap({DATA:JSON.stringify({columns:4,rows:4,tileSize:8,indices:Array(16).fill(0),walls:Array.from({length:16},(_,i)=>i%4===2?1:0),images:[{width:1,height:1,pixels:[0]}]})});const image=a.createImage({WIDTH:3,HEIGHT:3});for(const[i,c]of [0,2,0,2,2,2,0,2,0].entries())a.setImagePixel({IMAGE:image,X:i%3,Y:(i/3)|0,COLOR:c});const id=a.createImageSprite({IMAGE:image,KIND:'Player'});a.setSpritePosition({ID:id,X:12,Y:12});a.setSpriteScale({ID:id,VALUE:2,ANCHOR:0});assert.equal(prop(a,id,'x'),p.scaleX);assert.equal(prop(a,id,'y'),p.scaleY);a.setSpriteProperty({ID:id,PROPERTY:'vx',VALUE:100});a._advance(.1);assert.equal(prop(a,id,'x'),p.contactX);assert.equal(prop(a,id,'vx'),p.contactVx);assert.equal(a.isHittingTile({ID:id,DIRECTION:2}),p.contactRight);a.setSpriteProperty({ID:id,PROPERTY:'sx',VALUE:.5});assert.equal(prop(a,id,'x'),p.resizedX);assert.equal(prop(a,id,'width'),p.resizedWidth);
});
test('original large scalar scales retain Fx.mul overflow before shifting in opaque hitboxes',async()=>{
 const p=await runPxtArcade(`let actor=sprites.create(img\`.222\n.222\n.222\n.222\`,SpriteKind.Player);actor.sx=16384;actor.sy=8192;let box=actor._hitbox;let ox=Fx.toFloat(box.ox);let oy=Fx.toFloat(box.oy);let width=Fx.toFloat(box.width);let height=Fx.toFloat(box.height);`);
 const a=new Arcade(new EventEmitter()),image=a.createImage({WIDTH:4,HEIGHT:4});a.drawImage({IMAGE:image,OP:'fillRect',X:1,Y:0,W:3,H:4,COLOR:2});const id=a.createImageSprite({IMAGE:image,KIND:'Player'});a.setSpriteProperty({ID:id,PROPERTY:'sx',VALUE:16384});a.setSpriteProperty({ID:id,PROPERTY:'sy',VALUE:8192});const box=a._wallHitbox(a._sprite(id));for(const[key,name]of [['left','ox'],['top','oy'],['width','width'],['height','height']])assert.equal(box[key],p[name],name);
});
