import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {loadExtensionClass} from './helpers/bw-extensions.mjs';
import {runPxtArcade} from './helpers/pxt-arcade-runtime.mjs';
const Arcade=loadExtensionClass('arcade');
function game(){return new Arcade(new EventEmitter());}
function actor(a){const id=a.createSprite({KIND:'Player',X:80,Y:60,WIDTH:1,HEIGHT:1});a.setSpritePosition({ID:id,X:80,Y:60});a.setSpriteProperty({ID:id,PROPERTY:'vx',VALUE:100});return id;}
const x=(a,id)=>a.spriteProperty({ID:id,PROPERTY:'x'});
const engine=(a)=>a.scenePhysicsEngine({SCENE:a.currentScene()});
const property=(a,e,p)=>a.physicsEngineProperty({ENGINE:e,PROPERTY:p});
test('scene and engine identities remain real resources, settings round fixed point and default only omitted arguments',()=>{
 const a=game(),scene=a.currentScene(),original=engine(a);assert.equal(a.currentScene(),scene);assert.equal(engine(a),original);
 for(const [args,expected] of [[{},[500,2,4]],[{MAX_SPEED:undefined,MIN_STEP:undefined,MAX_STEP:undefined},[0,0,0]],[{MAX_SPEED:null,MIN_STEP:null,MAX_STEP:null},[0,0,0]],[{MAX_SPEED:10.49,MIN_STEP:-.51,MAX_STEP:8388608},[10,-1,-8388608]]]){const e=a.createPhysicsEngine(args);for(const [i,p] of ['maxSpeed','minStep','maxStep'].entries())assert.equal(property(a,e,p),expected[i]);assert.notEqual(e,original);}
 a.pushScene();assert.notEqual(a.currentScene(),scene);assert.notEqual(engine(a),original);a.popScene();assert.equal(a.currentScene(),scene);assert.equal(engine(a),original);
});
test('new empty engines do not adopt existing sprites; switching restores memberships and retained scene assignment',()=>{
 const a=game(),scene=a.currentScene(),old=engine(a),first=actor(a),fresh=a.createPhysicsEngine({});a.setScenePhysicsEngine({SCENE:scene,ENGINE:fresh});a._advance(.1);assert.equal(x(a,first),80);const second=actor(a);a._advance(.1);assert.equal(x(a,first),80);assert.equal(x(a,second),90);
 a.setScenePhysicsEngine({SCENE:scene,ENGINE:old});a._advance(.1);assert.equal(x(a,first),90);assert.equal(x(a,second),90);
 a.pushScene();a.setScenePhysicsEngine({SCENE:scene,ENGINE:fresh});a._advance(.1);assert.equal(x(a,second),90);a.popScene();a._advance(.1);assert.equal(x(a,first),90);assert.equal(x(a,second),100);
});
test('settings affect real movement and actual step stalls produce a named diagnostic',()=>{
 const a=game(),id=actor(a),e=engine(a);a.setPhysicsEngineProperty({ENGINE:e,PROPERTY:'maxSpeed',VALUE:20.25});a._advance(.1);assert.equal(a.spriteProperty({ID:id,PROPERTY:'vx'}),20.25);assert.equal(x(a,id),82.0234375);
 const r=new EventEmitter(),b=new Arcade(r),diagnostics=[];r.on('ARCADE_RUNTIME_DIAGNOSTIC',d=>diagnostics.push(d));const who=actor(b),be=engine(b);b.setPhysicsEngineProperty({ENGINE:be,PROPERTY:'maxStep',VALUE:0});b._advance(.1);assert.equal(x(b,who),80);assert.equal(diagnostics[0].code,'physics-step-no-progress');b.setPhysicsEngineProperty({ENGINE:be,PROPERTY:'minStep',VALUE:1.75});b.setPhysicsEngineProperty({ENGINE:be,PROPERTY:'maxStep',VALUE:1.125});b._advance(.1);assert.equal(diagnostics.at(-1).minStep,1.75);assert.equal(diagnostics.at(-1).maxStep,1.125);
});
const motions=[{speed:20.25,min:.75,max:1.5,dt:.1},{speed:1000,min:1,max:8,dt:.003},{speed:1000,min:1,max:8,dt:.2},{speed:-3.6,min:2,max:4,dt:.1},{speed:0,min:2,max:4,dt:.1},{speed:500,min:0,max:4,dt:.1},{speed:500,min:0,max:0,dt:.1},{speed:500,min:.5,max:.75,dt:1/30}];
test('actual original PXT confirms constructor/settings, membership switching and retained scene identity',async()=>{
 const source=`let home=game.currentScene();let original=home.physicsEngine as ArcadePhysicsEngine;let originalSpeed=original.maxSpeed;let originalMin=original.minStep;let originalMax=original.maxStep;
 let explicitUndefined=new ArcadePhysicsEngine(undefined,undefined,undefined);let undefinedSpeed=explicitUndefined.maxSpeed;let undefinedMin=explicitUndefined.minStep;let undefinedMax=explicitUndefined.maxStep;let fresh=new ArcadePhysicsEngine(20.25,.75,1.5);let roundedSpeed=fresh.maxSpeed;let roundedMin=fresh.minStep;let roundedMax=fresh.maxStep;
 let first=sprites.create(img\`2\`,SpriteKind.Player);first.setPosition(80,60);first.vx=100;home.physicsEngine=fresh;fresh.move(.1);let parkedFirst=first.x;
 let second=sprites.create(img\`2\`,SpriteKind.Player);second.setPosition(80,60);second.vx=100;fresh.move(.1);let movedSecond=second.x;let secondVelocity=second.vx;
 home.physicsEngine=original;original.move(.1);let movedFirst=first.x;let parkedSecond=second.x;
 game.pushScene();let childDifferent=game.currentScene()!=home;let childEngineDifferent=game.currentScene().physicsEngine!=original;home.physicsEngine=fresh;game.currentScene().physicsEngine.move(.1);let hiddenSecond=second.x;game.popScene();let homeRestored=game.currentScene()==home;let assignedRestored=game.currentScene().physicsEngine==fresh;fresh.move(.1);let resumedSecond=second.x;
 fresh.maxSpeed=-3.6;fresh.minStep=.499;fresh.maxStep=8388608;let negativeSpeed=fresh.maxSpeed;let fractionalMin=fresh.minStep;let overflowMax=fresh.maxStep;`+motions.map((c,i)=>`\ngame.pushScene();let e${i}=new ArcadePhysicsEngine(${c.speed},${c.min},${c.max});game.currentScene().physicsEngine=e${i};let s${i}=sprites.create(img\`2\`,SpriteKind.Player);s${i}.setPosition(80,60);s${i}.vx=100;s${i}.vy=-50;e${i}.move(${c.dt});let motionX${i}=s${i}.x;let motionY${i}=s${i}.y;let motionVx${i}=s${i}.vx;let motionVy${i}=s${i}.vy;game.popScene()`).join('');
 const p=await runPxtArcade(source),a=game(),scene=a.currentScene(),old=engine(a);for(const [name,key] of [['originalSpeed','maxSpeed'],['originalMin','minStep'],['originalMax','maxStep']])assert.equal(property(a,old,key),p[name]);const undefinedEngine=a.createPhysicsEngine({MAX_SPEED:undefined,MIN_STEP:undefined,MAX_STEP:undefined});for(const [name,key] of [['undefinedSpeed','maxSpeed'],['undefinedMin','minStep'],['undefinedMax','maxStep']])assert.equal(property(a,undefinedEngine,key),p[name]);const fresh=a.createPhysicsEngine({MAX_SPEED:20.25,MIN_STEP:.75,MAX_STEP:1.5});for(const [name,key] of [['roundedSpeed','maxSpeed'],['roundedMin','minStep'],['roundedMax','maxStep']])assert.equal(property(a,fresh,key),p[name]);const first=actor(a);a.setScenePhysicsEngine({SCENE:scene,ENGINE:fresh});a._advance(.1);assert.equal(x(a,first),p.parkedFirst);const second=actor(a);a._advance(.1);assert.equal(x(a,second),p.movedSecond);assert.equal(a.spriteProperty({ID:second,PROPERTY:'vx'}),p.secondVelocity);a.setScenePhysicsEngine({SCENE:scene,ENGINE:old});a._advance(.1);assert.equal(x(a,first),p.movedFirst);assert.equal(x(a,second),p.parkedSecond);a.pushScene();assert.equal(a.currentScene()!=scene,p.childDifferent);assert.equal(engine(a)!=old,p.childEngineDifferent);a.setScenePhysicsEngine({SCENE:scene,ENGINE:fresh});a._advance(.1);assert.equal(x(a,second),p.hiddenSecond);a.popScene();assert.equal(a.currentScene()==scene,p.homeRestored);assert.equal(engine(a)==fresh,p.assignedRestored);a._advance(.1);assert.equal(x(a,second),p.resumedSecond);for(const [key,value,name] of [['maxSpeed',-3.6,'negativeSpeed'],['minStep',.499,'fractionalMin'],['maxStep',8388608,'overflowMax']]){a.setPhysicsEngineProperty({ENGINE:fresh,PROPERTY:key,VALUE:value});assert.equal(property(a,fresh,key),p[name]);}for(const [i,c] of motions.entries()){a.pushScene();const e=a.createPhysicsEngine({MAX_SPEED:c.speed,MIN_STEP:c.min,MAX_STEP:c.max});a.setScenePhysicsEngine({SCENE:a.currentScene(),ENGINE:e});const id=actor(a);a.setSpriteProperty({ID:id,PROPERTY:'vy',VALUE:-50});a._advance(c.dt);for(const [field,key] of [['motionX','x'],['motionY','y'],['motionVx','vx'],['motionVy','vy']])assert.ok(a.spriteProperty({ID:id,PROPERTY:key})===p[field+i],key+' settings case'+i);a.popScene();}
});

test('manual resource metadata, runtime isolation and project restarts invalidate old refs',()=>{const r=new EventEmitter(),a=new Arcade(r),other=game(),held=a.currentScene(),old=engine(a);for(const op of ['currentScene','scenePhysicsEngine','createPhysicsEngine','physicsEngineProperty','setPhysicsEngineProperty','setScenePhysicsEngine'])assert.ok(a.getInfo().blocks.some(b=>b.opcode===op));assert.deepEqual(a.getInfo().menus.physicsEngineProperties.items,['maxSpeed','minStep','maxStep']);assert.equal(other.scenePhysicsEngine({SCENE:held}).bwUndefined,true);r.emit('PROJECT_START');assert.notEqual(a.currentScene(),held);assert.notEqual(engine(a),old);assert.equal(a.scenePhysicsEngine({SCENE:held}).bwUndefined,true);});
