// SPDX-License-Identifier: Apache-2.0
//
// The Code tab must still round-trip every SPIKE block after the merge.
//
// SB3Creator.runtimeOp() looks an opcode up in RUNTIME_EXTENSIONS and returns
// null when there is no entry — at which point the block is simply not emitted.
// The vendored registry is pinned and still describes the five pre-merge
// extensions, so the unified entry is derived from the shipping extension and
// merged over it. These are the two properties that arrangement has to hold:
//
//   1. the derived entry matches the extension that actually ships, so the
//      checked-in JSON cannot go stale against the palette; and
//   2. every opcode the migration can produce has an entry, so no project
//      loses blocks in the Code tab by being migrated.
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {resolve, dirname} from 'node:path';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {quietConsole} from './helpers/quiet-console.mjs';
import {buildEntry, render} from '../scripts/spike/gen-runtime-ops.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const require = createRequire(import.meta.url);

quietConsole();

const opsPath = resolve(root, 'overlay/scratch-gui/src/lib/spike-runtime-ops.js');
const checkedIn = (await import(opsPath)).default;
const ledger = require('./fixtures/spike-legacy-ledger.json');
const migration = require('../overlay/scratch-vm/src/extension-support/spike-legacy-migration.js');

test('the checked-in ops match the extension that ships', () => {
    assert.deepEqual(checkedIn, buildEntry(),
        'run: node scripts/spike/gen-runtime-ops.mjs');
    // Rendered exactly as the generator renders it, so "regenerate" is always
    // a no-op diff when nothing changed.
    assert.equal(readFileSync(opsPath, 'utf8'), render(buildEntry()));
});

test('every opcode the migration can produce has a registry entry', () => {
    // The regression this exists to prevent: a legacy block migrates onto a
    // unified opcode, and the Code tab silently drops it because the pinned
    // registry never heard of it.
    const missing = [];
    for (const [legacyId, ext] of Object.entries(ledger.extensions)) {
        for (const block of ext.blocks) {
            const resolved = migration.resolveOpcode(`${legacyId}_${block.opcode}`);
            const opcode = resolved.opcode.slice('spikeprime_'.length);
            if (!checkedIn.ops[opcode]) missing.push(`${legacyId}_${block.opcode} -> ${opcode}`);
        }
    }
    assert.deepEqual(missing, [], 'these would stop round-tripping through the Code tab');
});

test('argument order is preserved, because the emitter reads them positionally', () => {
    assert.deepEqual(checkedIn.ops.motorRunFor.args, ['PORT', 'DIRECTION', 'VALUE', 'UNIT']);
    assert.deepEqual(checkedIn.ops.setLightMatrixPixel.args, ['PORT', 'X', 'Y', 'BRIGHTNESS']);
    assert.deepEqual(checkedIn.ops.getDistanceIn.args, ['PORT', 'UNIT']);
});

test('block kinds map to the three sb3-creator knows', () => {
    const kinds = new Set(Object.values(checkedIn.ops).map(op => op.kind));
    for (const kind of kinds) {
        assert.ok(['command', 'reporter', 'boolean', 'hat'].includes(kind), `unknown kind ${kind}`);
    }
    assert.equal(checkedIn.ops.isConnected.kind, 'boolean');
    assert.equal(checkedIn.ops.whenGesture.kind, 'hat');
    assert.equal(checkedIn.ops.getBatteryLevel.kind, 'reporter');
    assert.equal(checkedIn.ops.displayClear.kind, 'command');
});

test('the four dead ids are dropped rather than left resolvable', () => {
    // Read as text: importing the module would pull in the 886 kB compiler.
    // What matters is that the deletion is written and reaches every call
    // site, which is what putting it in this module buys.
    const door = readFileSync(
        resolve(root, 'overlay/scratch-gui/src/lib/sb3-creator-register-art.js'), 'utf8');
    assert.match(door, /SB3Creator\.RUNTIME_EXTENSIONS\.spikeprime = spikeRuntimeOps;/,
        'the unified entry must be merged in');
    assert.match(door, /delete SB3Creator\.RUNTIME_EXTENSIONS\[legacyId\];/,
        'the legacy entries must be removed');
    for (const legacyId of migration.LEGACY_IDS) {
        assert.ok(!Object.prototype.hasOwnProperty.call(checkedIn.ops, legacyId));
    }
});

test('the vendored registry is not edited', () => {
    // It is judged byte-for-byte against the sb3-creator pin. If this merge is
    // ever "simplified" into editing it, that gate fails somewhere far from
    // here; saying so at the scene is cheaper.
    const vendored = readFileSync(
        resolve(root, 'overlay/scratch-gui/src/lib/sb3-creator-runtime.js'), 'utf8');
    assert.match(vendored.slice(0, 200), /GENERATED by scripts\/gen-runtime-registry\.mjs/);
    assert.ok(vendored.includes('"spikeprimeble"'),
        'the vendored file still describes the pre-merge world, and that is correct: ' +
        'it is pinned, and the unified entry is merged over it at runtime');
});
