// Generated by scripts/preserve-paterson-lab.mjs. Adapted Microsoft/Paterson code, MIT.
// Original, adaptations and licence: static/guests/paterson-fat12/. Routine test, not DOS.
export const PATERSON_FAT12_BYTES = Object.freeze([184,0,0,142,216,142,208,188,0,240,184,0,1,142,192,187,0,6,190,3,0,186,188,10,232,32,0,232,1,0,244,137,247,209,239,1,247,38,139,57,247,198,1,0,116,8,209,239,209,239,209,239,209,239,129,231,255,15,195,198,6,0,5,1,86,137,247,209,238,1,222,1,254,209,239,38,139,60,115,13,209,226,209,226,209,226,209,226,131,231,15,235,4,129,231,0,240,9,215,38,137,60,94,195]);
