/*
 * irtower.h — a LEGO RCX infrared tower, as a gate.
 *
 * Clean-room. Sources: docs/RCX-IR-TOWER-FIRMWARE.md in this repository,
 * Kekoa Proudfoot's "RCX Internals" (1998), and component datasheets. No
 * other tower firmware was read; see ../README.md for the full source list.
 *
 * The whole device is one line of RCX Internals:
 *
 *     "The infrared signal is generated by inverting the serial data and
 *      modulating it with a 38 kHz carrier. Serial zeros generate light,
 *      while serial ones do not."
 *
 *     IR LED drive = carrier(38 kHz) AND NOT(host TXD)
 *
 * so there is no baud rate here, no framing, no buffer and no state. That is
 * deliberate and is what makes the same binary work at 2400 8-O-1 and at the
 * 4800 8-N-1 firmdl3 uses: a gate has nothing to be told.
 */
#ifndef IRTOWER_H
#define IRTOWER_H

#include <stdbool.h>
#include <stdint.h>

/*
 * board.h is the per-board constants header — boards/<board>/board.h — and is
 * found because the build puts exactly one board directory on the include
 * path. That is the only place a board name appears in the build.
 */
#include "board.h"

/* Gate modes. Compile-time, not runtime: on an 8-bit part the poll loop is the
 * whole program and must not contain a branch it can never take. */
#define IRT_GATE_SOFTWARE 0 /* poll TXD, call carrier_on/off */
#define IRT_GATE_HARDWARE 1 /* the peripheral ANDs the pin itself; zero CPU */

#ifndef IRT_GATE_MODE
#error "board.h must define IRT_GATE_MODE as IRT_GATE_SOFTWARE or IRT_GATE_HARDWARE"
#endif

#ifndef IRT_RX_WIRED_THROUGH
#define IRT_RX_WIRED_THROUGH 0
#endif

#define IRT_CARRIER_HZ_DEFAULT 38000u

/*
 * Duty cycle. The datasheet passband figures are quoted at 50 %, so that is
 * the default; lower duty buys LED peak current back at some cost in range
 * (Vishay 80069 §"carrier duty cycle": 50 % at 50 mA gives 30 m, 10 % at
 * 200 mA gives 32 m — the trade is nearly flat, which is why it is a
 * parameter and not a constant).
 */
#define IRT_DUTY_PERCENT_DEFAULT 50

typedef struct {
    uint32_t carrier_hz;
    uint8_t  duty_percent;
} irt_config;

typedef struct {
    uint32_t carrier_achieved_mhz; /* millihertz, as reported by the port */
    int32_t  carrier_error_ppm;    /* achieved vs requested, signed */
    uint8_t  gate_mode;
    uint32_t gate_poll_hz;         /* 0 when the gate is in hardware */
} irt_status;

/* Requested vs achieved, in parts per million. Exposed because the test suite
 * re-derives every board's recorded error with it rather than trusting a
 * number someone typed into a header. */
int32_t irt_carrier_error_ppm(uint32_t achieved_mhz, uint32_t requested_hz);

/* Bring the carrier up and leave the LED dark. Returns what the board got. */
irt_status irt_init(const irt_config *cfg);

/*
 * One pass of the gate. Empty on a hardware-gated board, and empty is the
 * point: the ideal port does nothing at runtime at all.
 */
void irt_service(void);

/* Gate forever. Never returns. */
void irt_run(void);

#endif /* IRTOWER_H */
