const UPDATE_TOOLBOX = 'scratch-gui/toolbox/UPDATE_TOOLBOX';

// Initial toolbox XML is null — it is generated by the blocks container after scratch-blocks
// loads (lazy). The reducer used to call makeToolboxXML(true) here, which requires
// scratch-blocks at import time and throws "scratch-blocks is not loaded yet".
const initialState = {
    toolboxXML: null
};

const reducer = function (state, action) {
    if (typeof state === 'undefined') state = initialState;
    switch (action.type) {
    case UPDATE_TOOLBOX:
        return Object.assign({}, state, {
            toolboxXML: action.toolboxXML
        });
    default:
        return state;
    }
};

const updateToolbox = function (toolboxXML) {
    return {
        type: UPDATE_TOOLBOX,
        toolboxXML: toolboxXML
    };
};

export {
    reducer as default,
    initialState as toolboxInitialState,
    updateToolbox
};
