/**
 * Prebuilt firmware images for the lessons whose family cannot compile in the
 * browser — the second half of D2.
 *
 * ## What this is for
 *
 * D2's first half closed on 2026-08-31: the five supported 8051 targets now
 * compile entirely in the browser through the vendored SDCC WASM chain, so an
 * 8051 lesson needs no network. Every other family still POSTs to
 * `stc-compiler.vercel.app/compile`, and the measured lesson corpus puts five
 * Wave-5 lessons and six Wave-3 lessons on AVR or RP2040 benches. Those
 * lessons declare `environment: "simulation"` — they promise a bench that runs
 * without hardware — and a bench that will not start without a network is not
 * that.
 *
 * The pattern is D7's, which closed the same shape for the machine benches: an
 * example that cannot be built in the browser SHIPS its image, with provenance,
 * and the runner uses it. `static/roms/*.bin` is the precedent; this is the
 * same idea keyed by the program rather than by the example, so a user EDIT
 * cannot silently get someone else's firmware.
 *
 * ## Why the key is the generated C, canonicalised
 *
 * The compile is a pure function of `(code, target, format)` — the same premise
 * the localStorage compile LRU rests on. A shipped image is therefore only
 * honest while the code it was built from is the code being asked for. So the
 * lookup:
 *
 *   1. narrows by `(target, format, canonical length)` — cheap, and enough to
 *      leave at most one candidate in a manifest this size;
 *   2. fetches the candidate and compares its stored canonical code to the
 *      generated one CHARACTER FOR CHARACTER before using the image.
 *
 * Step 2 is the authority; the SHA-256 in the manifest is provenance and the
 * drift gate's instrument, not a runtime dependency. That deliberately keeps
 * the whole path free of `crypto.subtle`, which does not exist outside a secure
 * context — an offline path that only works on https would be a poor joke.
 *
 * ### The one thing that has to be normalised away, and how we know it is safe
 *
 * `generateC({debug: true})` IS NOT BYTE-STABLE across two parses of the same
 * program. Measured 2026-08-31: parsing `program.bw` mints fresh random block
 * ids, and `debug: true` writes them into the `@bw yield` lines of the marker
 * header — three differing lines on `73-voltmeter`, seven on
 * `nano03-two-tasks`, and the line COUNT identical in every case. Nothing else
 * moves.
 *
 * Those ids live only inside a C block comment, and the compiled output confirms
 * it: the same program parsed twice, compiled twice, gave BYTE-IDENTICAL images
 * both times (`nano03-two-tasks` 2472 bytes, `pico02-pot-print` 1992 bytes) —
 * while the returned symbol tables differed, in exactly the echoed `block`
 * field and nowhere else.
 *
 * So {@link canonicalCode} blanks the id token in each `@bw yield` line and the
 * key is the result. Nothing else is normalised: if any other part of the C
 * changed, the program changed, and the image must not be used.
 *
 * The stale ids do not travel: the runner reads the yield map from ITS OWN
 * generated C (`readYieldMap(c)`) and joins to the symbol table on
 * `(task, state)`, which is the only key both halves speak — bw-board's
 * `avr8js-debug.js` and `rp2040js-debug.js` index `${task.name}/${y.state}`
 * and never look at `block`. The build script therefore DELETES the echoed
 * `block` field from every shipped symbol table rather than shipping an id that
 * belongs to a parse nobody will ever repeat.
 *
 * Any edit to the program changes the emitted C, the exact compare misses, and
 * the build falls through to the normal route: local SDCC for the five 8051
 * targets, the hosted service otherwise — with the hosted route's existing
 * honest failure when there is no network. The prebuilt image never stands in
 * for a program nobody compiled.
 *
 * ## Why not pre-seed the localStorage LRU
 *
 * That was the other candidate mechanism and it is worse on four counts.
 * (a) The LRU holds SIX entries and evicts on quota, so a shipped image could
 * silently disappear and take the lesson's offline promise with it — and the
 * cache swallows quota errors by design, which is right for a cache and wrong
 * for a shipped asset. (b) It is per-origin, per-browser and empty on a first
 * visit, so seeding it needs startup code that writes every image anyway.
 * (c) Its keys embed the full C source, so seeding costs the C twice — once in
 * the key, once in the payload. (d) A cache entry carries no provenance, so the
 * panel could not say WHY it did not use the network. The LRU keeps doing its
 * own job (a user's own repeat compiles); this is a separate, read-only lookup.
 *
 * Generated by `scripts/build-lesson-images.mjs`. The manifest and the images
 * are gated by `test/shipped-lesson-images.test.mjs`.
 *
 * @module
 */

/**
 * Board name -> compiler target. The compile service accepts chip names
 * (`atmega328p`), not board names (`arduino-nano`).
 *
 * SHARED WITH `debug-runner.js`, which imports it from here rather than
 * keeping its own copy. Two copies of this map is how a shipped image built
 * for `atmega328p` would quietly stop matching a runner that had started
 * asking for `arduino-nano`.
 */
export const COMPILE_TARGET = {
    'arduino-nano': 'atmega328p', 'arduino-uno': 'atmega328p',
    'atmega328p': 'atmega328p', 'atmega168p': 'atmega168p',
    'arduino-mega': 'atmega2560',
    'pico': 'rp2040',
    'stm32f030': 'stm32f030',
    'eater6502': 'eater6502'
};

/** The five 8051 parts the browser toolchain compiles locally (D2, first half). */
export const LOCAL_8051_TARGETS = new Set([
    'stc12c5a60s2', 'stc12c5a16s2', 'stc15f2k60s2', 'stc15w408as', 'stc89c52rc'
]);

/** @param {string} device the project's declared DEVICE, any case */
export function compileTargetFor (device) {
    const lower = String(device || 'stc12c5a60s2').toLowerCase();
    return COMPILE_TARGET[lower] || lower;
}

/**
 * `bin` is the service's name for a raw image. It refuses `uf2` outright
 * ("format must be ihx, hex or bin"), which once made every Pico compile fail
 * with the status stuck on a stale RUNNING label.
 *
 * @param {string} device the project's declared DEVICE, any case
 */
export function compileFormatFor (device) {
    const lower = String(device || '').toLowerCase();
    return (lower === 'pico' || lower === 'stm32f030') ? 'bin' : 'ihx';
}

/** Where the generated manifest and its images live under the app's own origin. */
export const SHIPPED_IMAGE_DIR = 'static/lesson-images/';

/**
 * The `@bw yield` marker line, whose fourth field is a percent-encoded block id
 * minted fresh by every parse. Matching the WHOLE line shape rather than just
 * the id keeps this from touching anything else that happens to look like a
 * token: the emitter writes `@bw yield <task> <state> <id> <kind>` and
 * `sb3-creator-c.js` parses it back with the same shape.
 */
const YIELD_MARKER = /(@bw yield\s+\w+\s+\d+\s+)(\S+)(\s+\S+)/g;

/**
 * The generated C with the one non-deterministic field blanked — see the header
 * for the measurement that says this is the ONLY one, and for why blanking it
 * cannot change which image is correct.
 *
 * @param {string} code
 * @returns {string}
 */
export function canonicalCode (code) {
    return String(code == null ? '' : code).replace(YIELD_MARKER, '$1-$3');
}

let manifestPromise = null;

/**
 * Resolve a path under the app's base URI.
 *
 * `document.baseURI` is what makes this work under the Pages sub-path
 * (`/brickwright-lite/`) as well as at a root. Outside a document — node tests
 * — the caller supplies `baseUri`.
 */
function resolve (rel, baseUri) {
    const base = baseUri || (typeof document !== 'undefined' ? document.baseURI : undefined);
    return base ? new URL(rel, base).href : rel;
}

/**
 * The manifest, fetched once per page and then remembered — including a
 * remembered FAILURE, as `null`. A build with no manifest (or a fetch a service
 * worker cannot satisfy) must cost one failed request, not one per Run.
 *
 * @param {string} [baseUri]
 * @returns {Promise<object|null>}
 */
export function loadShippedManifest (baseUri) {
    if (manifestPromise) return manifestPromise;
    manifestPromise = (async () => {
        try {
            const res = await fetch(resolve(`${SHIPPED_IMAGE_DIR}manifest.json`, baseUri));
            if (!res.ok) return null;
            const json = await res.json();
            return json && Array.isArray(json.images) ? json : null;
        } catch {
            return null;
        }
    })();
    return manifestPromise;
}

/** Test seam: forget the remembered manifest (and its remembered failure). */
export function resetShippedManifest () {
    manifestPromise = null;
}

/**
 * A prebuilt image for exactly this program, or null.
 *
 * Returns the same shape the hosted `/compile` response has, so `build()` can
 * treat both identically, plus a `provenance` block the panel says out loud.
 *
 * @param {string} code the generated C, exactly as it would be POSTed
 * @param {string} target compiler target (`atmega328p`, `rp2040`, …)
 * @param {string} format `ihx` or `bin`
 * @param {string} [baseUri]
 * @returns {Promise<object|null>}
 */
export async function shippedImageFor (code, target, format, baseUri) {
    if (typeof code !== 'string' || !code) return null;
    const manifest = await loadShippedManifest(baseUri);
    if (!manifest) return null;
    const canonical = canonicalCode(code);
    const candidates = manifest.images.filter(e =>
        e && e.target === target && e.format === format && e.codeLength === canonical.length);
    for (const entry of candidates) {
        let payload;
        try {
            const res = await fetch(resolve(SHIPPED_IMAGE_DIR + entry.file, baseUri));
            if (!res.ok) continue;
            payload = await res.json();
        } catch {
            continue;
        }
        // The authority. A length match is an index, not an identity.
        if (!payload || payload.code !== canonical) continue;
        return {
            success: true,
            base64: payload.base64,
            symbols: payload.symbols,
            bytes: payload.bytes,
            format: payload.format,
            f_cpu: payload.f_cpu,
            provenance: {
                exampleId: entry.exampleId,
                target: entry.target,
                format: entry.format,
                builtAt: manifest.builtAt,
                toolchain: entry.toolchain,
                service: manifest.service,
                codeSha256: entry.codeSha256,
                programSha256: entry.programSha256
            }
        };
    }
    return null;
}

/**
 * The sentence the panel shows when a prebuilt image was used.
 *
 * It has to say three things and no more: that nothing was compiled, what the
 * image was built from and when, and what makes it stop applying. The last
 * clause is the one that keeps this honest — a reader who edits the program
 * must not be left believing the prebuilt image still describes it.
 *
 * @param {object} provenance from {@link shippedImageFor}
 * @param {'en'|'de'} [lang]
 */
export function provenanceSentence (provenance, lang = 'en') {
    if (!provenance) return '';
    const {exampleId, target, builtAt, toolchain} = provenance;
    if (/^de/i.test(lang)) {
        return `Dieses Abbild ist für "${exampleId}" vorkompiliert (${target}, ` +
            `${toolchain || 'Toolchain nicht vermerkt'}, ${builtAt || 'Datum nicht vermerkt'}) ` +
            `und wurde ohne Netzwerk verwendet. Sobald du das Programm änderst, ` +
            `passt es nicht mehr und es wird neu übersetzt.`;
    }
    return `This image is prebuilt for "${exampleId}" (${target}, ` +
        `${toolchain || 'toolchain not recorded'}, built ${builtAt || 'date not recorded'}) ` +
        `and was used without the network. Edit the program and it no longer ` +
        `matches, so it will be compiled fresh.`;
}
