/* Generated by hand, one per board: see facts.h for why there are three. */
#include "irtower.h"
#include "facts.h"

const irt_board_facts irt_facts_host_sim = {
    IRT_BOARD_NAME,
    IRT_BOARD_CLOCK_HZ,
    IRT_CARRIER_TARGET_HZ,
    IRT_CARRIER_DIVISOR,
    IRT_CARRIER_DIVISOR_SCALE,
    IRT_CARRIER_ACHIEVED_MHZ,
    IRT_CARRIER_ERROR_PPM,
    IRT_CARRIER_DUTY_NUM,
    IRT_CARRIER_DUTY_DEN,
    IRT_GATE_MODE,
    IRT_GATE_POLL_HZ,
    IRT_GATE_JITTER_NS,
    IRT_RX_WIRED_THROUGH,
};
